# Generated by Django 5.0 on 2023-12-10 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizsystem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrecord',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
